version: "3"
services:
  post-service:
    container_name: post-service
    build:
      context: ./post-service
      dockerfile: ./post-service/Docerfile
    volumes:
      - ./post-service:/app
      - ./post-service/nodemon.json:/app/nodemon.json
      - /app/dist
      - /app/node_modules
    ports:
      - "7000:7000"
    expose:
      - "7000"
  # user-service:
  #   container_name: user-service
  #   build: ./user-service
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - user-service:/app
