version: "3"
services:
  gateway:
    build: "./gateway"
    volumes:
      - ./gateway:/app
    ports:
      - "8000:8000"
    depends_on:
      - gateway-redis
    environment:
      REDIS_SECRET: redissecret

  user-service:
    build: "./user-service"
    volumes:
      - ./user-service:/app
    ports:
      - "3000:3000"
    depends_on:
      - user-service-db
      - gateway
    environment:
      PORT: 3000
      DATABASE_URL: mysql://mysql:mysql@user-service-db:3306/users

  note-service:
    build: "./note-service"
    volumes:
      - ./note-service:/app
    ports:
      - "3001:3001"
    depends_on:
      - note-service-db
      - gateway
    environment:
      PORT: 3001
      DATABASE_URL: mysql://mysql:mysql@note-service-db:3306/notes

  note-service-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: notes
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always
    ports:
      - "5432:3306"
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - 5432

  user-service-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: users
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always
    ports:
      - "5433:3306"
    volumes:
      - mysqltwo:/var/lib/mysql
    expose:
      - 5433

  gateway-redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  mysql:
    name: prisma-db-users
  mysqltwo:
    name: prisma-db-notes
