version: "3"
services:
  gateway:
    build: "./gateway"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - gateway-redis
    env_file:
      - ./env/redis.env

  user-service:
    build: "./user-service"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - user-service-db
      - gateway
    env_file:
      - ./env/users.env

  note-service:
    build: "./note-service"
    volumes:
      - ./note-service:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - note-service-db
      - gateway
    env_file:
      - ./env/notes.env

  note-service-db:
    image: mysql
    env_file:
      - ./env/notes-db.env
    restart: always
    ports:
      - "5432:3306"
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - 5432

  user-service-db:
    image: mysql
    env_file:
      - ./env/users-db.env
    restart: always
    ports:
      - "5433:3306"
    volumes:
      - mysqltwo:/var/lib/mysql
    expose:
      - 5433

  gateway-redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

volumes:
  mysql:
  mysqltwo:
