version: "3"
services:
  gateway:
    build: "./gateway"
    volumes:
      - ./gateway:/opt/app
    ports:
      - "8000:8000"
    depends_on:
      - gateway-redis
    environment:
      REDIS_SECRET: redissecret
  user-service:
    build: "./user-service"
    volumes:
      - ./user-service:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - user-service-db
      - gateway
  post-service:
    build: "./post-service"
    volumes:
      - ./post-service:/opt/app
    ports:
      - "3001:3001"
    depends_on:
      - post-service-db
      - gateway
  post-service-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: posts
    ports:
      - "5432:5432"
  user-service-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user
    ports:
      - "5433:5433"
  gateway-redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
